language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8
script:
  - sbt clean coverage test
  - sbt 'docs/tut'
  - sbt 'readme/tut'
after_success:
  - sbt coverageReport
  - bash <(curl -s https://codecov.io/bash) -t 47609994-e0cd-4f3b-a28d-eb558142c3bb
