dist: xenial
language: scala

scala:
- 2.11.12
- 2.12.10
- 2.13.0

jdk:
- openjdk8

before_install:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    openssl aes-256-cbc -K $encrypted_37b99bd39158_key -iv $encrypted_37b99bd39158_iv -in secret_key.asc.enc -out secret_key.asc -d;
    gpg --import --batch --passphrase "$PGP_PASSPHRASE" secret_key.asc;
  fi
- export PATH=${PATH}:./vendor/bundle

install:
- rvm use 2.6.5 --install --fuzzy
- gem install jekyll -v 4

stages:
  - test
  - validation
  - deploy

jobs:
  include:
    - stage: validation
      script:
        - sbt ++$TRAVIS_SCALA_VERSION clean validateDocs validateCoverage
    - stage: deploy
      if: branch = master AND type != pull_request
      name: "Publish artifacts"
      script:
        - bash <(curl -s https://codecov.io/bash)
        - if grep -q "SNAPSHOT" version.sbt; then
            sbt ++$TRAVIS_SCALA_VERSION publish;
          else
            sbt orgUpdateDocFiles;
            git reset --hard HEAD;
            git clean -f;
            git checkout master;
            git pull origin master;
            sbt release;
            sbt docs/publishMicrosite;
          fi
      scala: 2.13.0
