language: scala
scala:
- 2.10.6
- 2.11.11
- 2.12.2
jdk:
- oraclejdk8
before_install:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc
   -K $encrypted_37b99bd39158_key -iv $encrypted_37b99bd39158_iv
   -in secring.gpg.enc -out secring.gpg -d; fi
script:
- sbt ++$TRAVIS_SCALA_VERSION orgScriptCI
- sbt 'examples/test'
after_success:
- bash <(curl -s https://codecov.io/bash)
- sbt ++$TRAVIS_SCALA_VERSION orgAfterCISuccess