name: Fetch
baseurl: /fetch
description: Simple & Efficient data access for Scala and Scala.js
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 1.0.0-RC2
org: 47 Degrees
markdown: kramdown
