name: Fetch
description: "Simple & Efficient data access for Scala and Scala.js"
github_owner: 47deg
baseurl: /fetch
style: fetch
highlight_theme: tomorrow
docs: true
markdown: redcarpet
cdn:
  url: https://rawgit.com/47deg/microsites/cdn/
collections:
  tut:
    output: true
